[package]
name = "load_balancer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "balancer"
path = "src/balancer.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[dependencies]
