name: Consensus Workbench CI
on: push
jobs:
  tests:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: cargo test --verbose
  clippy:
    runs-on: [self-hosted]
    steps:
      - name: Install Linux requirements
        run: |
          apt_dependencies="git curl libssl-dev pkg-config libudev-dev libv4l-dev clang"
          echo "Run apt update and apt install the following dependencies: $apt_dependencies"
          sudo apt update
          sudo apt install -y $apt_dependencies
      - name: Check clippy
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
              toolchain: nightly
              components: clippy
              failure-mode: warnings
        - uses: Swatinem/rust-cache@v1
        - run: cargo +nightly clippy --all-targets --all-features -- -D warnings
  format:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: rustfmt
      - uses: Swatinem/rust-cache@v1
      - run: cargo fmt -- --check
