name: Consensus Workbench CI
on: push
jobs:
  tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: cargo test --verbose
  clippy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
      - uses: Swatinem/rust-cache@v1
      - run: cargo +nightly clippy
  format:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: rustfmt
      - uses: Swatinem/rust-cache@v1
      - run: cargo fmt -- --check
