name: Consensus Workbench CI
on: push
jobs:
  tests:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: cargo test --verbose
  clippy:
    runs-on: [nomad]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            failure-mode: warnings
      - uses: Swatinem/rust-cache@v1
      - run: cargo +nightly clippy --all-targets --all-features -- -D warnings
  format:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: rustfmt
      - uses: Swatinem/rust-cache@v1
      - run: cargo fmt -- --check
